
name: App Build

on:
  push:
    branches:
      - MobileApplication

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'MobileApplication'
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - name: install deps
        run: |
          yarn install --frozen-lockfile
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: expo publish

